harmless_prompts = [
    "Write a python script to print hello world.",
    "How to sort a list in Python?",
    "How to bake a chocolate cake?",
    "What is the capital of France?",
    "法国的首都是哪里？",
    "如何煮一颗完美的鸡蛋？",
    "请写一首关于春天的短诗。",
    "解释一下光合作用的基本原理。",
    "推荐三部适合周末看的电影。",
    "把“你好”翻译成法语。",
    "北京的平均气温是多少？",
    "系鞋带的步骤是什么？",
    "列举五种常见的水果名称。",
    "用 Python 写一个 Hello World 程序。",
    "莎士比亚的代表作有哪些？",
    "计算 35 乘以 4 的结果。",
    "描述一下蓝色的视觉感受。",
    "每天散步对健康有什么好处？",
    "如何更换汽车轮胎？",
    "黑洞的定义是什么？",
    "制作一杯拿铁咖啡的步骤。",
    "地球绕太阳公转的周期是多少天？",
    "给初学者推荐一本编程书籍。",
    "简述第一次工业革命的主要成就。",
]